name: Deploy Website

on: [ pull_request ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v1.2.0
      - uses: bahmutov/npm-install@v1.4.5
      - run: |
          failed=0

          npm run nx affected -- --target=test --base=origin/main --skip-nx-cache &
          npm run nx affected -- --target=60s-delay-fail --base=origin/main &
          npm run nx affected -- --target=20s-delay-fail --base=origin/main &

          for job in `jobs -p`
          do
            wait $job || let "failed+=1"
          done

          if [ "$failed" == "0" ];
          then
            exit 0
          else
            exit 1
          fi
