name: Deploy Website

on: [ pull_request ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v1.2.0
      - uses: bahmutov/npm-install@v1.4.5
      - run: |
          pids=()

          npx nx affected --target=test --base=origin/main &
          pids+=($!)

          npx nx affected --target=60s-delay-fail --base=origin/main &
          pids+=($!)

          npx nx affected --target=20s-delay-fail --base=origin/main &
          pids+=($!)

          for pid in "${pids[@]}"; do
            wait "$pid"
          done
