name: Deploy Website

on: [pull_request]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    name: Building affected apps
#    steps:
#      - uses: actions/checkout@v1.2.0
#      - uses: bahmutov/npm-install@v1.4.5
#      - run: npm run nx affected -- --target=build --base=origin/main
#  test:
#    runs-on: ubuntu-latest
#    name: Testing affected apps
#    steps:
#      - uses: actions/checkout@v1.2.0
#      - run: git rev-parse HEAD
#      - uses: bahmutov/npm-install@v1.4.5
#      - run: npm run nx affected -- --target=test --base=origin/main
#  lint:
#    runs-on: ubuntu-latest
#    name: Linting affected apps
#    steps:
#      - uses: actions/checkout@v1.2.0
#      - uses: bahmutov/npm-install@v1.4.5
#      - run: npm run nx affected -- --target=lint --base=origin/main
#  e2e:
#    runs-on: ubuntu-latest
#    name: E2E testing affected apps
#    steps:
#      - uses: actions/checkout@v1.2.0
#      - uses: bahmutov/npm-install@v1.4.5
#      - run: npm run nx affected -- --target=e2e --base=origin/main

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
    with:
      number-of-agents: 4
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci
        npx nx affected --target=build --parallel=3
        npx nx affected --target=e2e --parallel=3
        npx nx affected --target=long-delay

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
    with:
      number-of-agents: 4
