name: Deploy Website

on: [ pull_request ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
    with:
      number-of-agents: 4
      environment-variables: |
        NX_CLOUD_DISTRIBUTED_EXECUTION_STOP_AGENTS_ON_FAILURE=false
        NX_VERBOSE_LOGGING=true
      parallel-commands-on-agents: |
        npm run nx affected -- --target=test --base=origin/main --skip-nx-cache
        npm run nx affected -- --target=60s-delay-fail --base=origin/main
        npm run nx affected -- --target=20s-delay-fail --base=origin/main

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
    with:
      number-of-agents: 4
