name: Deploy Website

on: [ pull_request ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v1.2.0
      - uses: bahmutov/npm-install@v1.4.5
      - run: |
          FAIL=0

          echo "starting"

          npx nx affected --target=test --base=origin/main --skip-nx-cache &
          npx nx affected --target=60s-delay-fail --base=origin/main &
          npx nx affected --target=20s-delay-fail --base=origin/main &

          for job in `jobs -p`
          do
            echo $job
            wait $job || let "FAIL+=1"
          done

          echo $FAIL

          if [ "$FAIL" == "0" ];
          then
            echo "success"
          else
            echo "failure ($FAIL)"
          fi
